/*
 * This source file was generated by the Gradle 'init' task
 */
package sh.kau.karabiner

import com.danrusu.pods4k.immutableArrays.ImmutableIntArray
import com.danrusu.pods4k.immutableArrays.immutableArrayOf

class App(private val filename: String) {

  operator fun invoke(): Int {

    val a: IntArray = intArrayOf(1, 2, 3)
    val b: Array<Int> = arrayOf(1, 2, 3)
    val c: ImmutableIntArray = immutableArrayOf(1, 2, 3)

    var lineCount: Int = 0
    Utils.forEachLine(filename) { line -> lineCount = lineCount + 1 }

    return lineCount
  }
}

fun main() {
  println("✗✗ App ${App("input.txt")()}")
}
