/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App(private val filename: String) {

  operator fun invoke(): Int {
    var lineCount = 0
    Utils.forEachLine(filename) { line ->
      lineCount++
    }
    return lineCount
  }
}

fun main() {
  println("App ${App("input.txt")()}")
}
