/*
 * This source file was generated by the Gradle 'init' task
 */
package sh.kau.karabiner

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {

  @Test
  fun day1() {
    assertTrue { Day1(("input.txt"))() == 1222801 }
  }
}
